### ISSUE TITLE
Final PDF look nowhere near the one shown in the repo gif

### ISSUE THREAD

**Issue by zenny** [gouvinb/cv-sample#6]
Hi @gouvinb 

After struggling a while, I could produce a pdf, but that does not look nowhere near the look that you could produce. 

What I did was:

```
git pull --recursive https://github.com/gouvinb/cv-sample.git
cd cv-sample
emacs resume.org
C-c C-e l-o
```

The produced resume.pdf is in 3 pages and looks like:
![pic-selected-211213-0756-17](https://user-images.githubusercontent.com/1653166/145766903-d3d61adb-3ce6-4b09-8343-6d17da4c6a2a.png)

There are no errors reported at all. Any clue to produce similar to yours or share if you have tweaked emacs config. Thanks and cheers,

PS: this does not seem to be emacs config specific because I tried with spacemacs, doom-emacs, scimax all with vanilla configuration. What exactly produces the single page pdf output like yours?

**Comment by gouvinb** [comment]
See https://github.com/gouvinb/cv-sample/issues/5#issuecomment-992435576
